name: Deploy Staging
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to push to staging'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RACK_ENV: test

    services:
      database:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name database

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Create database role
        run: docker exec database bash -c "PGPASSWORD=postgres psql -U postgres -c \"create role admin with createdb login password 'admin'\""

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3
          bundler-cache: true

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Setup database
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/dclund-test"
          PGPASSWORD: postgres
        run: |
          createdb -h localhost -p 5432 -U postgres dclund-test
          bundle exec rake db:migrate

      - name: Run tests
        id: run-tests
        env:
          DATABASE_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/dclund-test
          FAT_BOY_DATABASE_URL: postgres://postgres:postgres@localhost:5432/dclund-test
        run: bundle exec rake
        continue-on-error: true

      - name: Notify Failure
        uses: appleboy/telegram-action@master
        if: steps.run-tests.outcome != 'success'
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: html
          message: |
            Staging deployment failed ❌
            Reason: Failing test suite
            Repo: ${{ github.repository }}
            Author: ${{ github.actor }}
            Commit: <a href="${{ github.event.head_commit.url }}">${{ github.event.head_commit.message }}</a>

      - name: Exit with failure status
        if: steps.run-tests.outcome != 'success'
        run: exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        id: deploy
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_STAGING_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Notify deployment
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: html
          message: |
            Staging deployment ${{ steps.deploy.outcome == 'success' && 'succeeded ✅' || 'failed ❌' }}
            Repo: ${{ github.repository }}
            Author: ${{ github.actor }}
            Branch: ${{ inputs.branch }}
