name: Deploy Production
on:
  push:
    branches: [master]

jobs:
  # TODO: test:

  deploy:
    runs-on: ubuntu-latest
    # needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dcl-metrics-be"
          heroku_email: ${{secrets.HEROKU_EMAIL}}

      - name: Notify deployment
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: html
          message: |
            Prod deployment ${{ job.status == 'success' && 'succeeded' || 'failed' }}
            Repo: ${{ github.repository }}/${{ github.ref_name }}
            Author: ${{ github.actor }}
            Commit: <a href="${{ github.event.head_commit.url }}">${{ github.event.head_commit.message }}</a>
