name: Deploy Staging
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to push to staging'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - uses: akhileshns/heroku-deploy@v3.12.12
        id: deploy
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_STAGING_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Notify deployment
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: html
          message: |
            Staging deployment ${{ steps.deploy.outcome == 'success' && 'succeeded ✅' || 'failed ❌' }}
            Repo: ${{ github.repository }}
            Author: ${{ github.actor }}
            Branch: ${{ inputs.branch }}
